# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate cros-codecs

Name:           rust-cros-codecs
Version:        0.0.6
Release:        %autorelease
Summary:        Hardware-accelerated codecs for Linux

License:        BSD-3-Clause
URL:            https://crates.io/crates/cros-codecs
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Hardware-accelerated codecs for Linux.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CONTRIBUTING.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+anyhow-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+anyhow-devel %{_description}

This package contains library source intended for building other packages which
use the "anyhow" feature of the "%{crate}" crate.

%files       -n %{name}+anyhow-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+backend-devel %{_description}

This package contains library source intended for building other packages which
use the "backend" feature of the "%{crate}" crate.

%files       -n %{name}+backend-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+byteorder-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+byteorder-devel %{_description}

This package contains library source intended for building other packages which
use the "byteorder" feature of the "%{crate}" crate.

%files       -n %{name}+byteorder-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+crc32fast-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+crc32fast-devel %{_description}

This package contains library source intended for building other packages which
use the "crc32fast" feature of the "%{crate}" crate.

%files       -n %{name}+crc32fast-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+drm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+drm-devel %{_description}

This package contains library source intended for building other packages which
use the "drm" feature of the "%{crate}" crate.

%files       -n %{name}+drm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+drm-fourcc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+drm-fourcc-devel %{_description}

This package contains library source intended for building other packages which
use the "drm-fourcc" feature of the "%{crate}" crate.

%files       -n %{name}+drm-fourcc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gbm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gbm-devel %{_description}

This package contains library source intended for building other packages which
use the "gbm" feature of the "%{crate}" crate.

%files       -n %{name}+gbm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gbm-sys-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gbm-sys-devel %{_description}

This package contains library source intended for building other packages which
use the "gbm-sys" feature of the "%{crate}" crate.

%files       -n %{name}+gbm-sys-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libva-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libva-devel %{_description}

This package contains library source intended for building other packages which
use the "libva" feature of the "%{crate}" crate.

%files       -n %{name}+libva-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+nix-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nix-devel %{_description}

This package contains library source intended for building other packages which
use the "nix" feature of the "%{crate}" crate.

%files       -n %{name}+nix-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+thiserror-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+thiserror-devel %{_description}

This package contains library source intended for building other packages which
use the "thiserror" feature of the "%{crate}" crate.

%files       -n %{name}+thiserror-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v4l2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v4l2-devel %{_description}

This package contains library source intended for building other packages which
use the "v4l2" feature of the "%{crate}" crate.

%files       -n %{name}+v4l2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+v4l2r-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v4l2r-devel %{_description}

This package contains library source intended for building other packages which
use the "v4l2r" feature of the "%{crate}" crate.

%files       -n %{name}+v4l2r-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vaapi-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vaapi-devel %{_description}

This package contains library source intended for building other packages which
use the "vaapi" feature of the "%{crate}" crate.

%files       -n %{name}+vaapi-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+zerocopy-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+zerocopy-devel %{_description}

This package contains library source intended for building other packages which
use the "zerocopy" feature of the "%{crate}" crate.

%files       -n %{name}+zerocopy-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
