# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate lz4_flex

Name:           rust-lz4_flex
Version:        0.13.0
Release:        %autorelease
Summary:        Fastest LZ4 implementation in Rust, no unsafe by default

License:        MIT
URL:            https://crates.io/crates/lz4_flex
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Fastest LZ4 implementation in Rust, no unsafe by default.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+checked-decode-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+checked-decode-devel %{_description}

This package contains library source intended for building other packages which
use the "checked-decode" feature of the "%{crate}" crate.

%files       -n %{name}+checked-decode-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+frame-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+frame-devel %{_description}

This package contains library source intended for building other packages which
use the "frame" feature of the "%{crate}" crate.

%files       -n %{name}+frame-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+nightly-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nightly-devel %{_description}

This package contains library source intended for building other packages which
use the "nightly" feature of the "%{crate}" crate.

%files       -n %{name}+nightly-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+safe-decode-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+safe-decode-devel %{_description}

This package contains library source intended for building other packages which
use the "safe-decode" feature of the "%{crate}" crate.

%files       -n %{name}+safe-decode-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+safe-encode-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+safe-encode-devel %{_description}

This package contains library source intended for building other packages which
use the "safe-encode" feature of the "%{crate}" crate.

%files       -n %{name}+safe-encode-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
