# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate binggan

Name:           rust-binggan
Version:        0.14.2
Release:        %autorelease
Summary:        Benchmarking library for stable Rust

License:        MIT
URL:            https://crates.io/crates/binggan
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Benchmarking library for stable Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bpu_trasher-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bpu_trasher-devel %{_description}

This package contains library source intended for building other packages which
use the "bpu_trasher" feature of the "%{crate}" crate.

%files       -n %{name}+bpu_trasher-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+branch_predictor-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+branch_predictor-devel %{_description}

This package contains library source intended for building other packages which
use the "branch_predictor" feature of the "%{crate}" crate.

%files       -n %{name}+branch_predictor-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+prettytable-rs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+prettytable-rs-devel %{_description}

This package contains library source intended for building other packages which
use the "prettytable-rs" feature of the "%{crate}" crate.

%files       -n %{name}+prettytable-rs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+real_blackbox-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+real_blackbox-devel %{_description}

This package contains library source intended for building other packages which
use the "real_blackbox" feature of the "%{crate}" crate.

%files       -n %{name}+real_blackbox-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+table_reporter-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+table_reporter-devel %{_description}

This package contains library source intended for building other packages which
use the "table_reporter" feature of the "%{crate}" crate.

%files       -n %{name}+table_reporter-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
