# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate virtio-media

Name:           rust-virtio-media
Version:        0.0.7
Release:        %autorelease
Summary:        Device support for virtio-media

License:        BSD-3-Clause
URL:            https://crates.io/crates/virtio-media
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Device support for virtio-media.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+simple-device-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+simple-device-devel %{_description}

This package contains library source intended for building other packages which
use the "simple-device" feature of the "%{crate}" crate.

%files       -n %{name}+simple-device-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
