# Generated by rust2rpm 28
%bcond check 1

%global crate libcras

Name:           rust-libcras
Version:        99.1.0
Release:        %autorelease
Summary:        Package is a proof of concept used by bugdotexe to conduct a research

License:        MIT
URL:            https://crates.io/crates/libcras
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
This package is a proof of concept used by bugdotexe to conduct a
research. It has been uploaded for test purposes only. Its only function
is to confirm the installation of the package on victim's machines. The
code is not malicious in any way and will be deleted after the research
survey has been concluded. I do not accept any liability for any direct,
indirect, or consequential loss or damage arising from use of, or
reliance on, this package.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
# FIXME: no license files detected
%license LICENSE.dependencies
%doc README.md
%{_bindir}/libcras

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
