name: Build RPM

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Tools
      run: dnf install -y dnf-plugins-core rpmdevtools createrepo_c

    - name: Get Files
      run: |
        for spec in SPECS/*.spec; do
          spectool -R --get-files --all $spec
        done

    - name: Create Local Repo
      run : |
        createrepo ${GITHUB_WORKSPACE}/RPMS &&
        echo "[local-rpm]" | tee /etc/yum.repos.d/local-rpm.repo
        echo "name=Local RPM Repository" | tee -a /etc/yum.repos.d/local-rpm.repo
        echo "baseurl=file://${GITHUB_WORKSPACE}/RPMS" | tee -a /etc/yum.repos.d/local-rpm.repo
        echo "enabled=1" | tee -a /etc/yum.repos.d/local-rpm.repo
        echo "gpgcheck=0" | tee -a /etc/yum.repos.d/local-rpm.repo

    - name: Build Dep RPM
      run: |
        PACKAGES=($(<SPECS/ORDER))
        for package in "${PACKAGES[@]}"; do
          dnf --refresh builddep -y SPECS/$package.spec &&
          rpmbuild --define "_topdir ${GITHUB_WORKSPACE}" -bp SPECS/$package.spec &&
          cargo2rpm --path BUILD/$package*/*/Cargo.toml buildrequires --with-check | sed 's/^/"/; s/$/"/' | xargs dnf --refresh install
          rpmbuild --define "_topdir ${GITHUB_WORKSPACE}" -bb SPECS/$package.spec &&
          createrepo --update ${GITHUB_WORKSPACE}/RPMS
        done

    - name: Build RPM
      run: |
        dnf --refresh builddep -y SPECS/!("rust-"*).spec &&
        rpmbuild --define "_topdir ${GITHUB_WORKSPACE}" -ba SPECS/!("rust-"*).spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rpm-package
        path: RPMS/
