name: Build RPM

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Checkout CrosVM Code
      uses: actions/checkout@v4
      with:
        repository: google/crosvm
        path: BUILD/crosvm
        submodules: recursive

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Build RPM
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace fedora:latest script -q -c "
          dnf install -y dnf-plugins-core rpmdevtools &&
          spectool --get-files --all SPECS/*.spec &&
          dnf builddep -y SPECS/*.spec &&
          setsid rpmbuild --define '_topdir /workspace' -ba SPECS/*.spec
        "

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rpm-package
        path: RPMS/
