name: Build RPM

on:
  - push

defaults:
  run:
    # GitHub Actions run without a TTY device. This is a workaround to get one,
    # based on https://github.com/actions/runner/issues/241#issuecomment-2019042651
    shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Checkout CrosVM Code
      uses: actions/checkout@v4
      with:
        repository: google/crosvm
        path: BUILD/crosvm
        submodules: recursive

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Build RPM
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace fedora:latest bash -c "
          dnf install -y dnf-plugins-core rpmdevtools &&
          spectool --get-files --all SPECS/*.spec &&
          dnf builddep -y SPECS/*.spec &&
          rpmbuild --define '_topdir /workspace' -ba SPECS/*.spec
        "

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rpm-package
        path: RPMS/
