name: Build RPM

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Restore RPM Cache
      uses: actions/cache/restore@v4
      with:
        path: RPMS
        key: ${{ runner.os }}-${{ github.event.repository.name }}-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: ${{ runner.os }}-${{ github.event.repository.name }}

    - name: Install Tools
      run: |
        rm /etc/yum.repos.d/fedora-cisco-openh264.repo
        dnf install -y rpmdevtools createrepo_c

    - name: Create Local Repo
      run : |
        mkdir -p RPMS
        createrepo RPMS
        echo "[local-rpm]" | tee /etc/yum.repos.d/local-rpm.repo
        echo "name=Local RPM Repository" | tee -a /etc/yum.repos.d/local-rpm.repo
        echo "baseurl=file://${GITHUB_WORKSPACE}/RPMS" | tee -a /etc/yum.repos.d/local-rpm.repo
        echo "enabled=1" | tee -a /etc/yum.repos.d/local-rpm.repo
        echo "gpgcheck=0" | tee -a /etc/yum.repos.d/local-rpm.repo

    - name: Build Dep RPM
      run: |
        set -euo pipefail
        PACKAGES=($(<SPECS/ORDER))
        for package in "${PACKAGES[@]}"; do
          if rpmspec -q --builtrpms SPECS/${package}.spec | while read -r name; do compgen -G "RPMS/*/${name}.rpm" > /dev/null || exit 1; done; then
            echo "Skipping ${package}"
            continue
          fi

          spectool --define "_topdir ${GITHUB_WORKSPACE}" -R --get-files --all SPECS/${package}.spec
          dnf --refresh builddep -y SPECS/${package}.spec
          rpmbuild --define "_topdir ${GITHUB_WORKSPACE}" -br SPECS/${package}.spec || dnf --refresh builddep -y SRPMS/*.buildreqs.nosrc.rpm && rm -f SRPMS/*.buildreqs.nosrc.rpm
          rpmbuild --define "_topdir ${GITHUB_WORKSPACE}" -bb SPECS/${package}.spec
          createrepo --update RPMS
        done

    - name: Build RPM
      run: |
        spectool --define "_topdir ${GITHUB_WORKSPACE}" -R --get-files --all SPECS/crosvm.spec
        dnf --refresh builddep -y SPECS/crosvm.spec
        rpmbuild --define "_topdir ${GITHUB_WORKSPACE}" -br SPECS/crosvm.spec || dnf --refresh builddep -y SRPMS/*.buildreqs.nosrc.rpm && rm -f SRPMS/*.buildreqs.nosrc.rpm
        rpmbuild --define "_topdir ${GITHUB_WORKSPACE}" -bb SPECS/crosvm.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rpm-package
        path: RPMS/

    - name: Save RPM Cache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: RPMS
        key: ${{ runner.os }}-${{ github.event.repository.name }}-${{ github.run_id }}-${{ github.run_attempt }}
